name: validate namespace compatibility
on:
  workflow_call:
    inputs:
      packageId:
        required: true
        description: 04t package version id to validate
        type: string

jobs:
  validate-namespace-compatibility:
    runs-on: ubuntu-latest
    steps:
      - name: Set environment variables
        run: |
          echo "SF_DISABLE_AUTOUPDATE=true" >> $GITHUB_ENV
          echo "SF_DISABLE_SOURCE_MEMBER_POLLING=true" >> $GITHUB_ENV
          echo "SF_DISABLE_TELEMETRY=true" >> $GITHUB_ENV
          echo "SF_PROJECT_AUTOUPDATE_DISABLE_FOR_PACKAGE_VERSION_CREATE=true" >> $GITHUB_ENV

      - name: Install sfdx and connect to DevHub
        run: |
          npm install --global @salesforce/cli@${{ vars.SFDX_VERSION }}
          echo ${{ secrets.DEVHUB_URL }} > sfdx_auth
          sf org login sfdx-url --sfdx-url-file sfdx_auth --set-default-dev-hub --alias hub
          sf config set target-dev-hub=hub --global

      - name: Checkout
        uses: actions/checkout@v4

      - name: Create scratch org
        run: sf org create scratch --definition-file config/project-scratch-def.json --alias scratch-org --set-default --duration-days 1

      - name: Check package installation
        run: sf package install --package ${{ inputs.packageId }} --wait 10

      - name: Deploy cross namespace tests
        run: |
          sf project deploy start --source-dir force-app/recipes/classes/setup
          sf project deploy start --source-dir force-app/test/namespace

      - name: Execute tests
        run: sf apex run test --result-format human --output-dir ./tests/apex --test-level RunLocalTests --wait 20

      - name: Delete scratch org
        if: always()
        run: sf org delete scratch --no-prompt
